export const DUMMY_PRODUCTS = [
  {
    name: "Nirvanaa 751 ANC",
    brand: "BOAT",
    color: "Black",
    price: "4499",
    description:
      "Wireless Headphone with 40 mm drivers, 65 Hours (54 Hours with ANC), Type C, Dual Compatibility",
    features: [
      "Bluetooth 5.0 connectivity",
      "Up to 20 hours of playtime",
      "IPX7 water resistance",
      "Touch control for easy operation",
    ],
    imageUrls: [
      "https://www.boat-lifestyle.com/cdn/shop/products/main3_b6563f96-f1a1-4915-b686-d4e37232ec3c_600x.png?v=1685707922",
      "https://www.boat-lifestyle.com/cdn/shop/files/61u81pV72AL._SY450_450x.jpg?v=1685707757",
      "https://www.boat-lifestyle.com/cdn/shop/files/71w3s2UJNlL._SY450_450x.jpg?v=1685707756",
      "https://www.boat-lifestyle.com/cdn/shop/files/81nMx6cWJJL._SY450_450x.jpg?v=1685707757",
    ],
    type: "overear",
  },
  {
    name: "Immortal 1300",
    brand: "BOAT",
    color: "Blue",
    price: "3499",
    description:
      "Immerse yourself in studio-quality sound with the Harmony studio headphones. Perfect for professional musicians and audiophiles seeking unparalleled audio fidelity.",
    features: [
      "High-fidelity sound reproduction",
      "Over-ear design for superior comfort",
      "Adjustable headband for a customized fit",
      "Detachable cable with inline microphone",
    ],
    imageUrls: [
      "https://www.boat-lifestyle.com/cdn/shop/products/IM1300_main_4_600x.png?v=1632715015",
      "https://www.boat-lifestyle.com/cdn/shop/products/IM1300-FI_Blue03_800x.png?v=1659425496",
      "https://www.boat-lifestyle.com/cdn/shop/products/IM1300-FI_Blue05_800x.png?v=1659425496",
      "https://www.boat-lifestyle.com/cdn/shop/products/IM1300-FI_Blue04_800x.png?v=1659425496",
    ],
    type: "overear",
  },
  {
    name: "Airdopes 131",
    brand: "BOAT",
    color: "Red",
    price: "899",
    description:
      "Stay motivated during workouts with the Rhythm sport neckband earphones. Designed for active lifestyles, these earphones provide secure fit and sweat resistance.",
    features: [
      "Flexible neckband for stability",
      "IPX6 water resistance",
      "40-hour battery life",
      "Built-in controls for music and calls",
    ],
    imageUrls: [
      "https://www.boat-lifestyle.com/cdn/shop/products/32011675-2ad8-4b99-9787-895caf201d28_600x.png?v=1642405569",
      "https://www.boat-lifestyle.com/cdn/shop/products/FeatureImagesAD1314XChargecopy2_800x.jpg?v=1702008197",
      "https://www.boat-lifestyle.com/cdn/shop/products/FeatureImagesAD131BV5.0copy2_800x.jpg?v=1702008197",
      "https://www.boat-lifestyle.com/cdn/shop/products/FeatureImagesAD131VAcopy2_800x.jpg?v=1702008197",
    ],
    type: "inear",
  },
  {
    name: "Sony WH-CH520",
    brand: "SONY",
    color: "Blue",
    price: "4500",
    description:
      "Dominate the gaming battlefield with the Pulse gaming headset. Featuring immersive sound and a noise-canceling microphone, it's the ultimate weapon for gamers.",
    features: [
      "With up to 50-hour battery life and quick charging, you’ll have enough power for multi-day road trips and long festival weekends.",
      "Great sound quality customizable to your music preference with EQ Custom on the Sony | Headphones Connect App.",
      "Boost the quality of compressed music files and enjoy streaming music with high quality sound through DSEE.",
      "Designed to be lightweight and comfortable for all-day use.",
    ],
    imageUrls: [
      "https://m.media-amazon.com/images/I/31QB73-5IEL.SX300_SY300_QL70_FMwebp.jpg",
      "https://m.media-amazon.com/images/I/81gqmwsufOL.SX679.jpg",
      "https://m.media-amazon.com/images/I/811UeUfPYdL.SX679.jpg",
      "https://m.media-amazon.com/images/I/91tTIC0vQML.SX679.jpg",
    ],
    type: "overear",
  },
  {
    name: "Sony MDR-EX155AP",
    brand: "SONY",
    color: "Black",
    price: "1099",
    description:
      "Get ready to feel the bass with BassX in-ear earphones. These earphones deliver deep, powerful bass and clear highs for an immersive listening experience.",
    features: [
      "Dynamic bass drivers",
      "Gold-plated 3.5mm connector",
      "Ergonomic design for noise isolation",
      "Multiple ear tip sizes included",
    ],
    imageUrls: [
      "https://m.media-amazon.com/images/I/61eqJoa4MBL.SX679.jpg",
      "https://m.media-amazon.com/images/I/61fPOSnDULL.SX679.jpg",
      "https://m.media-amazon.com/images/I/611FHnItrxL.SX679.jpg",
      "https://m.media-amazon.com/images/I/61k-gSFwiaL.SX679.jpg",
    ],
    type: "inear",
  },
  {
    name: "Sony WF-C500",
    brand: "SONY",
    color: "Black",
    price: "5990",
    description:
      "Cut the cords and enjoy true freedom with Echo true wireless earbuds. These compact earbuds offer premium sound quality and intuitive touch controls.",
    features: [
      "Auto-pairing technology",
      "Compact charging case",
      "Up to 6 hours of playtime",
      "Sweat and water-resistant design",
    ],
    imageUrls: [
      "https://m.media-amazon.com/images/I/61gr7ExN6ML.SX679.jpg",
      "https://m.media-amazon.com/images/I/615YbV+-iAL.SX679.jpg",
      "https://m.media-amazon.com/images/I/41aopR2UT2L.SX679.jpg",
      "https://m.media-amazon.com/images/I/71WlmdNuJfL.SX679.jpg",
    ],
    type: "inear",
  },
  {
    name: "Immortal IM1300",
    brand: "BOAT",
    color: "Black Sabre",
    price: "3299",
    description:
      "Enjoy gaming sessions like you own the stage with IM 1300 that offers dual connectivity modes – 2.4GHz ultra low latency via dongle and Bluetooth v5.1 Response Frequency 20Hz-20KHz",
    features: [
      "Wireless 3D Spatial Sound experience",
      "Enjoy boAt Signature Sound",
      "Dual mics enhance versatility",
      "Vibrant 3-color breathing LEDs",
    ],
    imageUrls: [
      "https://m.media-amazon.com/images/I/71kqL+rxM1L._SX679_.jpg",
      "https://m.media-amazon.com/images/I/61nLbNBLSSL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/61vCpImv1aL._SX679_.jpg",
    ],
    type: "overear",
  },
  {
    name: "Airdopes 141",
    brand: "BOAT",
    color: "Black",
    price: "999",
    description:
      "Playback- Enjoy an extended break on weekends with your favourite episodes on stream, virtue of a playback time of up to 42 hours including the 6 hours nonstop playtime for earbuds.",
    features: [
      "Real-time audio with BEAST mode",
      "Built-in mics ensure clarity",
      "boAt Signature Sound immersion",
      "Type C interface for convenience",
    ],
    imageUrls: [
      "https://m.media-amazon.com/images/I/61KNJav3S9L._SX679_.jpg",
      "https://m.media-amazon.com/images/I/61mEqp7RZXL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/61vBE3t4x1L._SX679_.jpg",
      "https://m.media-amazon.com/images/I/61rM6cHlA1L._SX679_.jpg",
    ],
    type: "inear",
  },
  {
    name: "Boult Z40",
    brand: "JBL",
    color: "Z40 Blue",
    price: "999",
    description:
      "60 hours of total playtime – Mammoth battery power makes the Z40 earbuds stop at nothing.",
    features: [
      "Fast charging, long playtime",
      "Crystal-clear calls with ENC",
      "Lag-free gaming experience",
      "Dynamic bass for thrill",
    ],
    imageUrls: [
      "https://m.media-amazon.com/images/I/71ITkeoYiTL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/61RZhhALCXL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/81cGL-pDOvL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/81hChe9P0XL._SX679_.jpg",
    ],
    type: "inear",
  },
  {
    name: "Stinger 2 Core",
    brand: "MARSHALL",
    color: "White",
    price: "3490",
    description:
      "60 hours of total playtime – Mammoth battery power makes the Z40 earbuds stop at nothing.",
    features: [
      "Official Xbox Licensed headset",
      "Lightweight comfort",
      "Swivel-to-mute noise-cancelling microphone",
      "Immersive in-game audio",
    ],
    imageUrls: [
      "https://m.media-amazon.com/images/I/51E5VhH13kL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/41tjarWAPnL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/5119wa9wb6L._SX679_.jpg",
      "https://m.media-amazon.com/images/I/517Fzdz1oFL._SX679_.jpg",
    ],
    type: "overear",
  },
  {
    name: "pTron Turbo TWS Earbuds",
    brand: "PTRON",
    color: "Blue",
    price: "699",
    description:
      "TWS Earbuds with AptSense 40ms Low-Latency Mobile Gaming | Immersive Sound with Deep Bass | 45 Hrs Playtime with the Charging Case | Ergo-fit Bluetooth Earphones with Touch Controls",
    features: [
      "Enhanced voice calls with TruTalk",
      "Versatile modes for entertainment",
      "Large dynamic drivers for clarity",
      "Snug fit, passive noise cancellation",
    ],
    imageUrls: [
      "https://m.media-amazon.com/images/I/61xVBaBYXkL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/71VyHS4f4sL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/71ZA-4qxYoL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/718GXTQpS5L._SX679_.jpg",
    ],
    type: "inear",
  },
  {
    name: "ZEB-BLITZ (WHITE)",
    brand: "ZEBRONICS",
    color: "White",
    price: "2399",
    description:
      "Experience DOLBY ATMOS with ZEB-BLITZ USB gaming headphones. Add more detail to the audio and get immersed into the game, like never before.",
    features: [
      "Long, braided USB connector cable",
      "Advanced Windows software for customization",
      "Powerful 50mm Neodymium magnet drivers",
      "Flexible, high-sensitivity microphone",
    ],
    imageUrls: [
      "https://m.media-amazon.com/images/I/61Wyl9B6XxL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/61rMZCYatzL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/71WX5c7bXqL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/6144GANCpVL._SX679_.jpg",
    ],
    type: "inear",
  },
  {
    name: "Zeb-Thunder",
    brand: "ZEBRONICS",
    color: "Red",
    price: "749",
    description:
      "Comfortable Design: Beat the workday blues with music on Zeb-Thunder wireless headphone that comes in an ergonomic design a perfect fit and design for long hours use. Microphone sensitivity -40dB ±1dB",
    features: [
      "Soft, comfortable earcups for all-day",
      "Adjustable headband for custom fit",
      "Extended 60hrs playback time",
      "Superior sound quality for immersion",
    ],
    imageUrls: [
      "https://m.media-amazon.com/images/I/71Jr1wUZ1EL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/71MrdRynjaL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/71B7ToK7QZL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/71lBsQYVwcL._SX679_.jpg",
    ],
    type: "onear",
  },
  {
    name: "FM-Earbuds-V5",
    brand: "MARSHALL",
    color: "Black",
    price: "2199",
    description:
      "V5 earphones with a microphone and unique stereo design, delivering powerful bass and stunningly clear vocals. Wireless earbuds with ear hooks work efficiently to reduce the ambient noise around you and ensure your voice is heard clearly during phone calls.",
    features: [
      "Long-lasting battery with quick charge",
      "Waterproof with secure ear hooks",
      "Stable Bluetooth 5.3 connection",
      "Dual LED power display",
    ],
    imageUrls: [
      "https://m.media-amazon.com/images/I/71apKGmHJTL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/71ST55byRfL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/71IJPdJaTpL._SX679_.jpg",
      "https://m.media-amazon.com/images/I/71QU4X76CPL._SX679_.jpg",
    ],
    type: "inear",
  },
];
